### ISSUE TITLE
ModuleNotFoundError: No module named 'hallo_models'

### ISSUE THREAD

**Issue by nitinmukesh** [yl4467/singer#1]
```
(venv) C:\aiai\singer>python scripts/inference_new.py --config configs/inference/inference.yaml --source_image examples/0001.jpg --driving_audio examples/0001.wav --output results/
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\aiai\singer\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
Traceback (most recent call last):
  File "C:\aiai\singer\scripts\inference_new.py", line 46, in <module>
    from models.models.audio_spectral_embed import MultiSpectralAttentionLayer
  File "C:\aiai\singer\models\models\audio_spectral_embed.py", line 7, in <module>
    from hallo_models.DWT_IDWT.DWT_IDWT_layer import DWT_2D, DWT_2D, IDWT_2D
ModuleNotFoundError: No module named 'hallo_models'
```

Also this is not working

```
(venv) C:\aiai\singer>pip install .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by yl4467** [comment]
hi, I have updated this code repository, please update the code and these issues should be resolved.

**Comment by nitinmukesh** [comment]
Thank you @yl4467 .
Now there is new error.

```
(venv) C:\aiai\singer>pip install .
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing c:\aiai\singer
  Preparing metadata (setup.py) ... done
Requirement already satisfied: accelerate==0.28.0 in c:\aiai\singer\venv\lib\site-packages (from singer==1.0.0) (0.28.0)
-----
Building wheels for collected packages: singer
  Building wheel for singer (setup.py) ... done
  Created wheel for singer: filename=singer-1.0.0-py3-none-any.whl size=116965 sha256=324bedc2fa19585943f6a588dbf55fc343c9f246d15f3aa488eaf534bf2525c8
  Stored in directory: C:\Users\nitin\AppData\Local\Temp\pip-ephem-wheel-cache-d79m2te3\wheels\b7\2b\da\051f5f441816153a2ab52a81dbbceeb0ce37a7c541e35a46c4
Successfully built singer
Installing collected packages: singer
Successfully installed singer-1.0.0
```

Error

```
(venv) C:\aiai\singer>python scripts/inference_new.py --config configs/inference/inference.yaml --source_image examples/0001.jpg --driving_audio examples/0001.wav --output results/
Traceback (most recent call last):
  File "C:\aiai\singer\scripts\inference_new.py", line 46, in <module>
    from models.models.audio_spectral_embed import MultiSpectralAttentionLayer
  File "C:\aiai\singer\venv\lib\site-packages\models\models\audio_spectral_embed.py", line 7, in <module>
    from models.DWT_IDWT.DWT_IDWT_layer import DWT_2D, DWT_2D, IDWT_2D
  File "C:\aiai\singer\venv\lib\site-packages\models\DWT_IDWT\DWT_IDWT_layer.py", line 6, in <module>
    import pywt
ModuleNotFoundError: No module named 'pywt'

```

**Comment by nitinmukesh** [comment]
To solve the above problem [ModuleNotFoundError: No module named 'pywt'] I used this but than the old problem came back

```
(venv) C:\aiai\singer>pip install PyWavelets
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting PyWavelets
  Downloading pywavelets-1.8.0-cp310-cp310-win_amd64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 16.8 MB/s eta 0:00:00
Requirement already satisfied: numpy<3,>=1.23 in c:\aiai\singer\venv\lib\site-packages (from PyWavelets) (1.26.4)
Installing collected packages: PyWavelets
Successfully installed PyWavelets-1.8.0

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```
```

(venv) C:\aiai\singer>python scripts/inference_new.py --config configs/inference/inference.yaml --source_image examples/0001.jpg --driving_audio examples/0001.wav --output results/
Traceback (most recent call last):
  File "C:\aiai\singer\scripts\inference_new.py", line 50, in <module>
    from models.models.unet_3d_revised import UNet3DConditionModel
  File "C:\aiai\singer\venv\lib\site-packages\models\models\unet_3d_revised.py", line 42, in <module>
    from hallo_models.DWT_IDWT.DWT_IDWT_layer import DWT_2D, IDWT_2D
ModuleNotFoundError: No module named 'hallo_models'
```

**Comment by nitinmukesh** [comment]
@yl4467 

Please suggest how to fix this issue.

**Comment by yl4467** [comment]
please install the pywt package by `pip install PyWavelets`  and update the code

**Comment by nitinmukesh** [comment]
Thank you
